---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: false
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 10m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
    - http://www.google.com/;google.com
    - https://www.apple.com/;apple.com
    - https://www.facebook.com;facebook
    - https://stmichaelsschoolportal.engagehosted.com;Engage
    - https://stmichaelsschool.3cx.co.uk:5001/;phones
    - http://print.stmichaelsschool.co.uk/Live_Mobile;PrintServer
    - https://app.century.tech/login/;century.tech
    - https://www.purplemash.com/sch/stmichaels;PurpleMash
    - https://play.ttrockstars.com/auth/school/student/60985;TTRS
    - https://login.mymaths.co.uk/login;MyMaths
    - 1.1.1.3;Safe DNS

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
