{
 "title": "Internet-WIFI",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "show tag values from \"uap\" with key=\"source\""
   },
   {
    "name": "Site",
    "query": "show tag values from \"uap\" with key=\"site_name\" where source =~ /$Controller$/"
   },
   {
    "name": "AP",
    "label": "UniFi AP:",
    "query": "show tag values from \"uap\" with key=\"name\"  where site_name =~ /$Site$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/)",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device_name Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "SELECT last(\"num_sta\") FROM \"uap_radios\" WHERE (\"device_name\" =~ /^$host$/ AND \"radio\" = 'na') AND $timeFilter GROUP BY time($__interval), \"device_name\"",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "Guests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "is_guest" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/ AND is_guest = \"true\")",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "probe_success{}", "legendFormat": "{{humanname}}" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE $timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/ GROUP BY \"channel\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients / AP Band",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ap_name $tag_radio_proto",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter  AND  ap_name =~ /$AP$/ AND site_name =~ /$Site$/) GROUP BY \"radio_proto\", \"ap_name\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  }
 ]
}